accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import UserLoginView

urlpatterns = [


    path('logout/', LogoutView.as_view(next_page="memory_list"), name='logout'),

    path('login/', UserLoginView.as_view(), name='login'),

]

memory_board/urls.py
from django.urls import path

from .views import MemoriesListView, MemoryDetailView, MemorySearchList, MemoryCreateView, MemoryDeleteView


urlpatterns = [

    path('', MemoriesListView.as_view(), name="memory_list"),
    path('detail/<slug:slug>/', MemoryDetailView.as_view(), name="memory_detail"),
    path('search/', MemorySearchList.as_view(), name="memory_search"),
    path('create/', MemoryCreateView.as_view(), name="memory_create"),
    path('<int:pk>/delete/', MemoryDeleteView.as_view(), name="memory_delete"),

]

places_memories/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),

    path('social-auth/', include('social_django.urls', namespace='social')),

    path('', include('memory_board.urls')),
    path('accounts/', include('accounts.urls')),

]

# Settings Media with Debug:
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


# ----- User ----- #

class User(AbstractUser):
    """ Model: User(Memories author) """

    avatar = models.URLField(
        verbose_name=_("Автар пользователя"),
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

memory_board/models.py
from django.db import models

from django.conf import settings
from django.urls import reverse

from slugify import slugify

from accounts.models import User


# ----- Models: Memory ----- #

class MemoryPlacesModel(models.Model):
    """ Model: Memory about places """

    title = models.CharField(
        verbose_name="Название места",
        max_length=128,
    )

    description = models.TextField(
        verbose_name="Описание места",
        max_length=2048,
        blank=True,
    )

    review = models.TextField(
        verbose_name="Воспоминание о месте",
        max_length=2048,
    )

    address = models.CharField(
        verbose_name="Адрес места",
        max_length=128,
    )

    data_published_memory = models.DateTimeField(
        verbose_name="Дата и время создания воспоминания",
        auto_now_add=True,
    )

    user = models.ForeignKey(
        verbose_name="Автор воспоминания",
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='memory_list',
        blank=True,
        null=True,
    )

    images = models.ImageField(
        verbose_name="Фотографии с впечатлениями",
        blank=True,
        null=True,
    )

    slug = models.SlugField(
        verbose_name="Slug воспоминания",
        max_length=128,
        unique=True,
        db_index=True,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("memory_detail", kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super(MemoryPlacesModel, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Воспоминание"
        verbose_name_plural = "Воспоминания"
        ordering = ["-data_published_memory"]

memory_board/forms.py
from django import forms

from .models import MemoryPlacesModel


# ----- Places Memory forms ----- #

class MemoryCreateForm(forms.ModelForm):
    """ Forms: Create remember Form """

    class Meta:

        model = MemoryPlacesModel

        fields = [
            "title",
            "address",
            "images",
            "description",
            "review",
        ]

accounts/views.py
from django.views.generic import TemplateView


# ------ User views ----- #

class UserLoginView(TemplateView):

    http_method_names = ('get', )
    template_name = 'places_memory/memory_list.html'

memory_board/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy

from django.views.generic.edit import CreateView, FormView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import MemoryPlacesModel
from .forms import MemoryCreateForm


# ----- Places memories views ----- #


class MemoriesListView(ListView):
    """ View: Display all users memories """

    model = MemoryPlacesModel
    template_name = "places_memory/memory_list.html"
    context_object_name = "memory_list"

    success_url = reverse_lazy("memory_list")
    login_url = 'memory_list'

    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        """
        Get contex_data for users memories:
        :param object_list: -
        :param kwargs: -
        :return: if user is authenticated - return user memories, else - Nothing([])
        """

        context = super().get_context_data(**kwargs)

        # Get all users memories from QuerySet:
        if self.request.user.is_authenticated:

            context["memory_list"] = self.get_queryset()
            context["memory_list_carousel"] = self.get_queryset()

        return context

    def get_queryset(self):
        """
        If user authenticated - return his memories:
        :return: user memories or []
        """
        if self.request.user.is_authenticated:

            return self.request.user.memory_list.all()
        else:
            return []


class MemoryDetailView(LoginRequiredMixin, DetailView):
    """ View: Display detail users memories """

    model = MemoryPlacesModel
    template_name = "places_memory/memory_detail.html"
    queryset = MemoryPlacesModel.objects.all()
    context_object_name = "memory_detail"

    slug_field = 'slug'

    def get_context_data(self, **kwargs):

        if self.object.user_id == self.request.user.id:
            context = super().get_context_data(**kwargs)

            return context
        else:
            return self.handle_no_permission()


class MemorySearchList(LoginRequiredMixin, ListView):
    """ View: Search memory """

    template_name = "places_memory/memory_list.html"
    context_object_name = "memory_list"

    paginate_by = 2

    def get_queryset(self):

        if self.request.user.is_authenticated:

            return MemoryPlacesModel.objects.filter(
                    title__icontains=self.request.GET.get('q')
                ).filter(
                user=self.request.user
            )

    def get_context_data(self, *, object_list=None, **kwargs):

        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:

            context["memory_list_carousel"] = MemoryPlacesModel.objects.filter(
                user=self.request.user
            ).order_by(
                'data_published_memory'
            )

        context['q'] = f"q={self.request.GET.get('q')}&"

        return context


class MemoryCreateView(LoginRequiredMixin, CreateView, FormView):
    """ View: Create memory """

    template_name = "places_memory/memory_create.html"
    form_class = MemoryCreateForm

    success_url = reverse_lazy("memory_list")

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        return context

    def post(self, request, *args, **kwargs):

        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):

        user_memory = form.save(commit=False)

        user_memory.user = self.request.user

        return super().form_valid(form=form)


class MemoryDeleteView(LoginRequiredMixin, DeleteView):
    """ View: Delete memory """

    model = MemoryPlacesModel
    template_name = "places_memory/memory_list.html"

    success_url = reverse_lazy("memory_list")

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """

        self.object = self.get_object()

        if self.request.user.id != self.object.user_id:
            return self.handle_no_permission()

        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>

    <!-- Bootstrap CSS and Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">


    <!-- Load CSS -->
    <link rel="stylesheet" href="{{ STATIC_URL }}memory_board/css/style.css" type="text/css" media="all">


    <!-- Font  Awesome -->
    <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
    />

    <!-- Load JS scripts for YandexMap -->
    <script type="module" src="{% static '/memory_board/js/create_address.js' %}"></script>
    <script src="https://api-maps.yandex.ru/2.1/?apikey=fcb7fea7-8f12-4d3b-bb75-b3bd6868da70&lang=ru_RU" type="text/javascript"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>

    <!-- JS-script -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>

    <title>YourPlacesRemember</title>

</head>

<body>

    <!-- Navbar -->
    {% csrf_token %}
    {% include 'include/navbar.html' %}

    <!-- DataPizza -->
    {% csrf_token %}
    {% block content %}

        Content Text

    {% endblock content %}

</body>

</html>

templates/include/navbar.html
<!-- Navbar -->

<nav class="navbar navbar-expand-lg bg-light">

    <div class="container-fluid">

        <a class="navbar-brand" href="{% url 'memory_list' %}">YourPlacesRemember</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                {% if request.user.is_authenticated %}
                    <img src="{{ request.user.avatar }}" alt="Avatar" class="avatar">
                {% endif %}

                <li class="nav-item dropdown">

                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {% if request.user.is_authenticated %}
                            {{ request.user.username }}
                        {% else %}
                            Войти на сайт
                        {% endif %}
                    </a>

                    <ul class="dropdown-menu">
                        {% if request.user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'memory_create' %}">Создать воспоминание</a>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Выход</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'social:begin' 'vk-oauth2' %}">Вход через Vk</a></li>
                            <li><a class="dropdown-item" href="{% url 'social:begin' 'google-oauth2' %}">Вход через Google+</a></li>
                        {% endif %}
                    </ul>

                </li>

            </ul>

            {% if request.user.is_authenticated %}
                <form class="d-flex" role="search" action="{% url 'memory_search' %}" method="get">
                    <input class="form-control me-2" type="search" placeholder="Название воспомнания" aria-label="Search" name="q">
                    <button class="btn btn-outline-success" type="submit">Поиск</button>
                </form>
            {% endif %}

        </div>

    </div>

</nav>

templates/places_memory/memory_create.html
{% extends 'base.html' %}
{% load static %}

<!-- DataPlacesRemember -->
{% block content %}

<div class="container">

    <main>

        <div class="py-5 text-center">
            <h2>Мое воспоминание...</h2>
        </div>

        <div class="row g-5">

            <div class="col-md-5 col-lg-4 order-md-last">
                <ul class="list-group mb-3">
                    <div>
                        <form method="post" class="user-update-form" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div id="map" class="map"></div>
                        </form>
                    </div>
                </ul>
            </div>

            <div class="col-md-7 col-lg-8">

                <h5 class="mb-3">Место воспоминания:</h5>

                <form method="post" class="user-update-form" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="col-sm-6">
                        <label for="id_title" class="form-label">Название места:</label>
                        <textarea class="form-control" name="title" id="id_title" placeholder="" required></textarea>
                    </div>

                    <div class="col-sm-6">
                        <br><label for="id_address" class="form-label">Адрес:</label></br>
                        <input type="text" name="address" class="form-control" id="id_address" placeholder value="" required="">
                    </div>

                    <div class="col-sm-6">
                        <br>Фотографии, связанные с этим местом:</br>
                        {{ form.images }}
                    </div>

                    <div class="col-sm-6">
                        <br><label for="id_description" class="form-label">Описание места:</label></br>
                        <textarea class="form-control" name="description" id="id_description" placeholder required=""></textarea>
                    </div>

                    <div class="col-12">
                      <br><label for="id_review" class="form-label">Ваши впечатления об этом месте:</label></br>
                        <textarea class="form-control" name="review" id="id_review" placeholder></textarea>
                    </div>

                    <div class="button_create">
                        <button class="w-100 btn btn-primary btn-lg" type="submit">Создать воспоминание</button>
                    </div>

                </form>
            </div>
        </div>
    </main>
</div>

{% endblock content %}

templates/places_memory/memory_detail.html
{% extends 'base.html' %}
{% load static %}

<!-- DataPlacesRemember -->
{% block content %}

    <script type="module" src="{% static '/memory_board/js/add_address.js' %}" id="address">{{ memory_detail.address }}</script>

    <div class="container overflow-hidden" id="detail-memory">

        <div class="row gy-5 row-cols-1 ">

            <div class="col">

                <div class="container" id="container_detail">
                    <div class="post">
                        <div class="post-image">
                            <img src="{{ memory_detail.images.url }}">
                        </div>
                        <div class="post-content">
                            <div class="post-header">
                                <h2>{{ memory_detail.title }}</h2>
                                <div class="post-meta">
                                    <time datetime="2019-04-01">{{ memory_detail.data_published_memory }}</time>
                                </div>

                                <div id="map_add"></div>

                            </div>
                            <p id="detail_p">
                                <b>Описание места:</b>
                                {{ memory_detail.description }}
                                <br><b>Впечатление о месте:</b>
                                <br>{{ memory_detail.review }}
                            </p>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

templates/places_memory/memory_list.html
{% extends 'base.html' %}
{% load static %}

<!-- DataPlacesRemember -->
{% block content %}

    <!-- If  user authenticated and have memory-->
    {% if request.user.is_authenticated %}

        {% if memory_list %}
            <main>
                {% if memory_list_carousel %}
                    <!-- Carousel memories-->
                    <div class="container-fluid memory-carousel">
                        <div id="carouselExampleCaptions" class="carousel slide carousel-fade">

                            <div class="carousel-inner">
                                {% for memory in memory_list_carousel|slice:':1' %}
                                    {% if memory.images %}
                                        <div class="carousel-item active">
                                            <img src="{{ memory.images.url }}" class="d-block w-100" alt="">
                                            <div class="carousel-caption d-none d-md-block">
                                                <p><a id="carousel_a" href="{{ memory.get_absolute_url }}">{{ memory.title }}</a></p>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}

                                {% for memory in memory_list_carousel|slice:'1:2' %}
                                    {% if memory.images %}
                                        <div class="carousel-item active">
                                            <img src="{{ memory.images.url }}" class="d-block w-100" alt="">
                                            <div class="carousel-caption d-none d-md-block">
                                                <p><a id="carousel_a"  href="{{ memory.get_absolute_url }}">{{ memory.title }}</a></p>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}

                                {% for memory in memory_list_carousel|slice:'2:3' %}
                                    {% if memory.images %}
                                        <div class="carousel-item active">
                                            <img src="{{ memory.images.url }}" class="d-block w-100" alt="">
                                            <div class="carousel-caption d-none d-md-block">
                                                <p><a id="carousel_a" href="{{ memory.get_absolute_url }}">{{ memory.title }}</a></p>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>

                            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                            </button>

                        </div>
                    </div>
                {% endif %}
            </main>

            <!-- User memories-->

            <div class="container">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

                    {% for memory in memory_list %}

                        <div class="col-md-6">

                            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">

                                <div class="col p-4 d-flex flex-column position-static">

                                    <h5 class="mb-0">
                                        {{ memory.title }}
                                    </h5>

                                    <div class="mb-1 text-muted">
                                        {{ memory.data_published_memory }}
                                    </div>

                                    <p class="card-text mb-auto">{{ memory.description|truncatechars:175 }}</p>

                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <button type="submit" onclick="window.location.href = '{{ memory.get_absolute_url }}';" class="btn btn-outline-info">Подробнее</button>
                                        </div>

                                        <form method="post" action="{% url 'memory_delete' pk=memory.pk %}">
                                            {% csrf_token %}
                                            <button type="submit" formaction="{% url 'memory_delete' pk=memory.pk %}" class="btn btn-success">Удалить</button>
                                        </form>
                                    </div>

                                </div>
                                {% if memory.images %}
                                    <div class="col-auto d-none d-lg-block">
                                        <img id="image_list" src="{{ memory.images.url }}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" loading="lazy">
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                    {% endfor %}
                </div>
            </div>
        {% endif %}

        {% if request.user.is_authenticated %}
            {% if not memory_list %}
                <!-- If  user authenticated and don't have memory-->
                <div class="container">
                    <h1 class="mt-5">К сожалению у Вас нет воспоминаний...</h1>
                    <p class="lead">Но вы можете прямо сейчас оставить свое первое воспоминание:</p>
                    <p><a id="firs_memory_a" href="{% url 'memory_create' %}">Оставить свое первое воспоминание</a></p>
                </div>
            {% endif %}
        {% endif %}

    {% else %}

    <!-- If user not authenticated -->
    <main class="px-8">
        <div class="container col-xxl-8 px-4 py-5">
            <div class="row flex-lg-row-reverse align-items-center g-5 py-5">

                <div class="col-10 col-sm-8 col-lg-6">
                    <img src="{% static 'memory_board/images/hello.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" loading="lazy" width="700" height="500">
                </div>

                    <div class="col-10 col-sm-8 col-lg-6">
                    <h3 class="display-5 fw-bold lh-1 mb-3">Запечатли и сохрани свои воспоминания</h3>
                    <p class="lead">
                        Для доступа к своим воспоминаниям, пройдите авторизацию через учетную запись Вконтакте или Google:
                    </p>

                        <div id="social" class="container social">
                            <a href="{% url 'social:begin' 'vk-oauth2' %}" class="btn">
                                <i class="fab fa-vk">
                                </i>
                            </a>
                            <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn">
                                <i class="fab fa-google">
                                </i>
                            </a>
                        </div>
                    </div>
                </div>

            </div>
          </div>
    </main>


    {% endif %}

{%  endblock content %}